apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: gitea
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 5Gi
